<script setup lang="ts">
const value = defineModel<number>({ required: true });

const handleInput = (event: Event) => {
  const input = event.target as HTMLInputElement;
  // Remove any non-numeric characters
  // I'm not great with regex so this was generated by ChatGPT.
  // A bug I'm stuck on is that typing any non numeric character will remove the entire value.
  // Please dont test me on regex. I will fail.
  const numericValue = input.value.replace(/[^0-9]/g, '');
  if (input.value !== numericValue) {
    input.value = numericValue;
  }
};
</script>

<template>
  <input v-model.number="value" type="number" @input="handleInput" />
</template>

<style scoped>
/* Remove the up and down arrows from the native input */
input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

input[type='number'] {
  -moz-appearance: textfield;
}
</style>
